from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib import colors
from datetime import datetime


def save_report_as_pdf(result, memo, action, filename="risk_report.pdf"):

    doc = SimpleDocTemplate(filename)
    styles = getSampleStyleSheet()

    content = []

    # 🧾 Clean memo
    def clean_memo(memo):
        memo = memo.replace("**", "")
        memo = memo.replace("###", "")
        memo = memo.replace("---", "")

        # Remove DATE line from LLM output
        lines = memo.split("\n")
        cleaned_lines = []
        for line in lines:
            if "DATE:" in line.upper():
                continue
            cleaned_lines.append(line)

        return "\n".join(cleaned_lines)

    # 🏷 Title
    content.append(Paragraph("Financial Risk Report", styles["Title"]))
    content.append(Spacer(1, 10))

    # Confidential note
    content.append(Paragraph("<b>Confidential – Internal Use Only</b>", styles["Normal"]))
    content.append(Spacer(1, 15))

    # Dynamic date (CORRECT one)
    content.append(Paragraph(
        f"Date: {datetime.now().strftime('%d %B %Y')}",
        styles["Normal"]
    ))
    content.append(Spacer(1, 12))

    # 📊 Table Data
    table_data = [
        ["Field", "Value"],
        ["Company", result["company"]],
        ["Risk Score", f"{result['risk_score']}/100"],
        ["Risk Level", result["risk_level"]],
        ["Recommended Action", action],
    ]

    # 📊 Table
    table = Table(table_data, colWidths=[170, 230])

    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.grey),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),

        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTNAME", (0, 1), (0, -1), "Helvetica-Bold"),

        ("ALIGN", (0, 0), (-1, -1), "LEFT"),

        ("GRID", (0, 0), (-1, -1), 0.5, colors.black),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.whitesmoke, colors.lightgrey]),

        ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
        ("TOPPADDING", (0, 0), (-1, -1), 8),
    ]))

    content.append(table)
    content.append(Spacer(1, 20))

    # 📄 Section Heading
    content.append(Paragraph("Risk Analysis Report", styles["Heading2"]))
    content.append(Spacer(1, 10))

    # Clean memo text
    memo_cleaned = clean_memo(memo)
    memo_cleaned = memo_cleaned.replace("\n", "<br/>")

    content.append(Paragraph(memo_cleaned, styles["Normal"]))

    # Footer
    content.append(Spacer(1, 20))
    content.append(Paragraph(
        "Generated by Financial Risk Monitoring System",
        styles["Italic"]
    ))

    # Build PDF
    doc.build(content)